services:
  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=$(echo 'Password1' | docker run --rm -i datalust/seq config hash)
    volumes:
      - ./data:/data
    ports:
      - "5341:80"
    image: datalust/seq:latest

PH=$(echo 'Password1' | docker run --rm -i datalust/seq config hash)

docker run \
  --name seq \
  -d \
  --restart unless-stopped \
  -e ACCEPT_EULA=Y \
  -e SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH" \
  -v ./data:/data \
  -p 5341:80 \
  datalust/seq

