services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH
    volumes:
      - ./data:/data
    ports:
      - "5341:5341"
      - "8081:80"
